name: whatsapp_assessment
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  animated_splash_screen: ^1.3.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  bloc: ^9.0.0
  build_runner: ^2.4.14
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen_runner: ^5.11.0
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  lint: ^2.8.0
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_gen:
  output: ./lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYBLACKITALIC.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYBOLD.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYHEAVYITALIC.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYLIGHTITALIC.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYMEDIUM.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYREGULAR.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYSEMIBOLDITALIC.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYTHINITALIC.otf
        - asset: assets/fonts/SFPro_Font/SFPRODISPLAYULTRALIGHTITALIC.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
  # To add custom fonts to your application
